# generated by datamodel-codegen:
#   filename:  medium_grade_workshop_month_export_products__models.yaml
#   timestamp: 2024-10-29T05:11:59+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Meta, Struct
from typing_extensions import Annotated


class ExportProduct(Struct):
    name: Optional[Annotated[str, Meta(description='Период')]] = None
    percent: Optional[Annotated[float, Meta(description='%')]] = None
    production: Optional[Annotated[float, Meta(description='Производство, т')]] = None
    shipped: Optional[Annotated[float, Meta(description='Отгружено, т')]] = None
    total: Optional[Annotated[float, Meta(description='т')]] = None


ExportProducts = Annotated[
    List[ExportProduct], Meta(description='Экспортная продукция')
]


class MediumGradeWorkshopMonthExportProductsGetParametersQuery(Struct):
    start_date: str
    end_date: str


class MediumGradeWorkshopMonthExportProductsGetResponseItem(Struct):
    isTotal: Optional[bool] = None
    values: Optional[List[str]] = None


MediumGradeWorkshopMonthExportProductsGetResponse = List[
    MediumGradeWorkshopMonthExportProductsGetResponseItem
]
