# generated by datamodel-codegen:
#   filename:  medium_grade_workshop_month_actions_with_inappropriate_production__models.yaml
#   timestamp: 2024-10-29T05:11:55+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Meta, Struct
from typing_extensions import Annotated


class ActionsWithInappropriateProductionItem(Struct):
    grade: Optional[Annotated[str, Meta(description='')]] = None
    name: Optional[Annotated[str, Meta(description='Градация')]] = None
    output: Optional[Annotated[float, Meta(description='выход, %')]] = None
    received: Optional[Annotated[float, Meta(description='получено, т')]] = None
    total: Optional[Annotated[float, Meta(description='Всего, т')]] = None


ActionsWithInappropriateProduction = Annotated[
    List[ActionsWithInappropriateProductionItem],
    Meta(description='Действия с несоответствующей продукцией'),
]


class MediumGradeWorkshopMonthActionsWithInappropriateProductionGetParametersQuery(
    Struct
):
    start_date: str
    end_date: str


class MediumGradeWorkshopMonthActionsWithInappropriateProductionGetResponseItem(Struct):
    isTotal: Optional[bool] = None
    values: Optional[List[str]] = None


MediumGradeWorkshopMonthActionsWithInappropriateProductionGetResponse = List[
    MediumGradeWorkshopMonthActionsWithInappropriateProductionGetResponseItem
]
