components:
  schemas:
    actions_with_inappropriate_production:
      description: Действия с несоответствующей продукцией
      items:
        properties:
          grade:
            description: ''
            type: string
          name:
            description: Градация
            type: string
          output:
            description: выход, %
            format: float
            type: number
          received:
            description: получено, т
            format: float
            type: number
          total:
            description: Всего, т
            format: float
            type: number
        type: object
      type: array
info:
  description: API ОТК
  title: '12136'
  version: 0.0.1
openapi: 3.0.3
paths:
  /medium_grade_workshop/month/actions_with_inappropriate_production/:
    get:
      description: Действия с несоответствующей продукцией
      parameters:
      - description: Начальная дата (в формате YYYY-MM-DD)
        in: query
        name: start_date
        required: true
        schema:
          example: '2024-08-31'
          format: date
          type: string
      - description: Конечная дата (в формате YYYY-MM-DD)
        in: query
        name: end_date
        required: true
        schema:
          example: '2024-08-31'
          format: date
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  properties:
                    isTotal:
                      nullable: true
                      type: boolean
                    values:
                      items:
                        type: string
                      type: array
                  type: object
                type: array
          description: Отправка данных
      summary: ССЦ Отчёт за месяц
      tags:
      - data
      - ccs
      - month
servers:
- url: https://localhost
