# generated by datamodel-codegen:
#   filename:  medium_grade_workshop_month_violation_of_technology_in_number_of_cases__models.yaml
#   timestamp: 2024-10-29T05:12:03+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Meta, Struct
from typing_extensions import Annotated


class ViolationOfTechnologyInNumberOfCase(Struct):
    SSC: Optional[Annotated[int, Meta(description='ССЦ')]] = None
    SSC_last_year: Optional[Annotated[int, Meta(description='ССЦ')]] = None
    UK: Optional[Annotated[int, Meta(description='УК')]] = None
    UK_SSC_total: Optional[Annotated[int, Meta(description='Всего УК ССЦ')]] = None
    UK_last_year: Optional[Annotated[int, Meta(description='УК')]] = None
    br1: Optional[Annotated[int, Meta(description='бр1')]] = None
    br2: Optional[Annotated[int, Meta(description='бр2')]] = None
    br3: Optional[Annotated[int, Meta(description='бр3')]] = None
    br4: Optional[Annotated[int, Meta(description='бр4')]] = None
    br_total: Optional[Annotated[int, Meta(description='Всего')]] = None
    name: Optional[Annotated[str, Meta(description='Нарушение в случаях')]] = None


ViolationOfTechnologyInNumberOfCases = Annotated[
    List[ViolationOfTechnologyInNumberOfCase],
    Meta(description='Нарушение технологии в случаях'),
]


class MediumGradeWorkshopMonthViolationOfTechnologyInNumberOfCasesGetParametersQuery(
    Struct
):
    start_date: str
    end_date: str


class MediumGradeWorkshopMonthViolationOfTechnologyInNumberOfCasesGetResponseItem(
    Struct
):
    isTotal: Optional[bool] = None
    values: Optional[List[str]] = None


MediumGradeWorkshopMonthViolationOfTechnologyInNumberOfCasesGetResponse = List[
    MediumGradeWorkshopMonthViolationOfTechnologyInNumberOfCasesGetResponseItem
]
