# generated by datamodel-codegen:
#   filename:  medium_grade_workshop_month_excel__models.yaml
#   timestamp: 2024-10-29T05:11:58+00:00

from __future__ import annotations

from msgspec import Struct


class MediumGradeWorkshopMonthExcelGetParametersQuery(Struct):
    start_date: str
    end_date: str
