# generated by datamodel-codegen:
#   filename:  medium_grade_workshop_month_defects_in_the_profiles__models.yaml
#   timestamp: 2024-10-29T05:11:58+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Meta, Struct
from typing_extensions import Annotated


class DefectsInTheProfile(Struct):
    name: Optional[Annotated[str, Meta(description='Название профиля')]] = None
    norm: Optional[Annotated[float, Meta(description='Норматив, %')]] = None
    percent: Optional[Annotated[float, Meta(description='%')]] = None
    percent_to_total_for_period: Optional[Annotated[float, Meta(description='%')]] = (
        None
    )
    summary: Optional[bool] = None
    total: Optional[Annotated[float, Meta(description='Всего, т')]] = None
    total_for_period: Optional[Annotated[float, Meta(description='Всего, т')]] = None


DefectsInTheProfiles = Annotated[
    List[DefectsInTheProfile], Meta(description='Брак по профилям')
]


class MediumGradeWorkshopMonthDefectsInTheProfilesGetParametersQuery(Struct):
    start_date: str
    end_date: str


class MediumGradeWorkshopMonthDefectsInTheProfilesGetResponseItem(Struct):
    isTotal: Optional[bool] = None
    values: Optional[List[str]] = None


MediumGradeWorkshopMonthDefectsInTheProfilesGetResponse = List[
    MediumGradeWorkshopMonthDefectsInTheProfilesGetResponseItem
]
