info:
  description: API ОТК
  title: '12136'
  version: 0.0.1
openapi: 3.0.3
paths:
  /medium_grade_workshop/month/excel/:
    get:
      description: ССЦ Отчёт за месяц - выгрузка в ексель
      parameters:
      - description: Начальная дата (в формате YYYY-MM-DD)
        in: query
        name: start_date
        required: true
        schema:
          example: '2024-08-01'
          format: date
          type: string
      - description: Конечная дата (в формате YYYY-MM-DD)
        in: query
        name: end_date
        required: true
        schema:
          example: '2024-08-31'
          format: date
          type: string
      responses:
        '200':
          description: Отправка данных
      summary: ССЦ Отчёт за месяц - выгрузка в ексель
      tags:
      - excel
servers:
- url: https://localhost
