# generated by datamodel-codegen:
#   filename:  medium_grade_workshop_month_defects_by_type_in_the_finished_grade__models.yaml
#   timestamp: 2024-10-29T05:11:56+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Meta, Struct
from typing_extensions import Annotated


class DefectsByTypeInTheFinishedGradeItem(Struct):
    name: Optional[Annotated[str, Meta(description='Вид дефекта')]] = None
    norm: Optional[Annotated[float, Meta(description='Норматив %')]] = None
    percent_to_total: Optional[Annotated[float, Meta(description='%')]] = None
    percent_to_total_for_period: Optional[Annotated[float, Meta(description='%')]] = (
        None
    )
    summary: Optional[bool] = None
    total: Optional[Annotated[float, Meta(description='Всего, т')]] = None
    total_for_period: Optional[
        Annotated[float, Meta(description='Всего, т. за период')]
    ] = None


DefectsByTypeInTheFinishedGrade = Annotated[
    List[DefectsByTypeInTheFinishedGradeItem],
    Meta(description='Брак по видам в готовом сорте'),
]


class MediumGradeWorkshopMonthDefectsByTypeInTheFinishedGradeGetParametersQuery(Struct):
    start_date: str
    end_date: str


class MediumGradeWorkshopMonthDefectsByTypeInTheFinishedGradeGetResponseItem(Struct):
    isTotal: Optional[bool] = None
    values: Optional[List[str]] = None


MediumGradeWorkshopMonthDefectsByTypeInTheFinishedGradeGetResponse = List[
    MediumGradeWorkshopMonthDefectsByTypeInTheFinishedGradeGetResponseItem
]
