# generated by datamodel-codegen:
#   filename:  medium_grade_workshop_month_violation_of_technology_in_tons__models.yaml
#   timestamp: 2024-10-29T05:12:04+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Meta, Struct
from typing_extensions import Annotated


class ViolationOfTechnologyInTon(Struct):
    name: Optional[Annotated[str, Meta(description='Нарушение в случаях')]] = None
    percent_for_last_year: Optional[
        Annotated[float, Meta(description='% за прошлый год')]
    ] = None
    percent_to_total: Optional[Annotated[float, Meta(description='%')]] = None
    percent_to_total_for_period: Optional[Annotated[float, Meta(description='%')]] = (
        None
    )
    total: Optional[Annotated[float, Meta(description='Всего, т')]] = None
    total_for_period: Optional[
        Annotated[float, Meta(description='Всего, т. за период')]
    ] = None


ViolationOfTechnologyInTons = Annotated[
    List[ViolationOfTechnologyInTon], Meta(description='Нарушение технологии в тоннах')
]


class MediumGradeWorkshopMonthViolationOfTechnologyInTonsGetParametersQuery(Struct):
    start_date: str
    end_date: str


class MediumGradeWorkshopMonthViolationOfTechnologyInTonsGetResponseItem(Struct):
    isTotal: Optional[bool] = None
    values: Optional[List[str]] = None


MediumGradeWorkshopMonthViolationOfTechnologyInTonsGetResponse = List[
    MediumGradeWorkshopMonthViolationOfTechnologyInTonsGetResponseItem
]
