# generated by datamodel-codegen:
#   filename:  medium_grade_workshop_month_measures__models.yaml
#   timestamp: 2024-10-29T05:12:01+00:00

from __future__ import annotations

from typing import List, Optional

from msgspec import Meta, Struct
from typing_extensions import Annotated


class Measure(Struct):
    last_year: Optional[Annotated[float, Meta(description='Прошлый год, %')]] = None
    month: Optional[Annotated[float, Meta(description='Месяц, %')]] = None
    name: Optional[Annotated[str, Meta(description='Название профиля')]] = None
    summary: Optional[bool] = None
    year: Optional[Annotated[float, Meta(description='Год, %')]] = None


Measures = Annotated[List[Measure], Meta(description='Выход меры')]


class MediumGradeWorkshopMonthMeasuresGetParametersQuery(Struct):
    start_date: str
    end_date: str


class MediumGradeWorkshopMonthMeasuresGetResponseItem(Struct):
    isTotal: Optional[bool] = None
    values: Optional[List[str]] = None


MediumGradeWorkshopMonthMeasuresGetResponse = List[
    MediumGradeWorkshopMonthMeasuresGetResponseItem
]
